### PR TITLE
Emit the warning if the `-Vstatistics` option isn't set

### LINKED ISSUE #45: Flamegraphs are empty without the `-Ystatistics` option
The compiler plugin doesn't generate useful data if you don't add the `-Ystatistics`.
It should fail the compilation or, at least, print a warning to inform the user to add the option.

### PR DESCRIPTION
**Pull request by danicheg**
Resolves #45.
The following warning will be emitted if the `Ystatistics` option isn't set:
```
[warn] `scalac-profiling` compiler plugin requires the option `-Ystatistics` to be enabled
```
By enabling the `-Xfatal-warnings` option, it will be an error:
```
[error] `scalac-profiling` compiler plugin requires the option `-Ystatistics` to be enabled
```

It's convenient to manage fatal behaviour with `-Xfatal-warnings`, but the output contains excessive debug information, causing that warning may go unnoticed. 
**UPD**: if users don't enable the `-P:scalac-profiling:show-profiles` option, the output is much consier.
WDYT @lolgab @sjrd @SethTisue?

### CODE REVIEW

File: plugin/src/main/scala/ch/epfl/scala/ProfilingPlugin.scala [hunk 1]
```diff
@@ -294,6 +295,16 @@ class ProfilingPlugin(val global: Global) extends Plugin {
         override def run(): Unit = {
           super.run()
 
+          if (!SettingsOps.areStatisticsEnabled(global)) {
+            val flagName = global.settings.Ystatistics.name.replace("-V", "-Y")
```
Comment (SethTisue) [inline plugin/src/main/scala/ch/epfl/scala/ProfilingPlugin.scala:299]: normally if `-V` is supported, it is canonical, and normally if a `-Y ` form exists as well, it is only a deprecated alias. So unless you want to argue otherwise, I should we be documenting and recommending the `-V` form?

Comment (danicheg) [reply plugin/src/main/scala/ch/epfl/scala/ProfilingPlugin.scala:299]: > normally if -V is supported, it is canonical, and normally if a -Y  form exists as well, it is only a deprecated alias.

Thanks! Is this Scala-version-specific logic?

Comment (som-snytt) [reply plugin/src/main/scala/ch/epfl/scala/ProfilingPlugin.scala:299]:
```
scala> settings.Ystatistics.name
val res1: String = -Vstatistics

scala> settings.Ystatistics.abbreviations
val res2: List[String] = List(-Ystatistics)
```

Comment (SethTisue) [reply plugin/src/main/scala/ch/epfl/scala/ProfilingPlugin.scala:299]: But in 2.12, 

```
scala 2.12.18> settings.Ystatistics.name
res0: String = -Ystatistics

scala 2.12.18> settings.Ystatistics.abbreviations
res1: List[String] = List()
```

Comment (lolgab) [reply plugin/src/main/scala/ch/epfl/scala/ProfilingPlugin.scala:299]: So just removing `.replace("-V", "-Y")` should give the right flag on all versions

Comment (danicheg) [reply plugin/src/main/scala/ch/epfl/scala/ProfilingPlugin.scala:299]: Yeah, perhaps this difference between `-Y` and `-V` is too subtle for the end users so we can show `-V` for 2.13 and `-Y` for 2.12. Any objections?

Comment (SethTisue) [reply plugin/src/main/scala/ch/epfl/scala/ProfilingPlugin.scala:299]: SGTM

Comment (SethTisue) [reply plugin/src/main/scala/ch/epfl/scala/ProfilingPlugin.scala:299]: I've submitted https://github.com/scalacenter/scalac-profiling/pull/52 to update the readme accordingly.

In the long run, it would be good to move the documentation in the blog post to some more permanent, updatable location. The old post could then have a note at the top redirecting readers to the current documentation. (This is what we did, for example, with https://www.lightbend.com/blog/scala-inliner-optimizer which eventually turned into https://docs.scala-lang.org/overviews/compiler-options/optimizer.html.)

**Review by SethTisue — APPROVED** [review]

**Comment by SethTisue** [comment]
@danicheg needs rebase

**Comment by danicheg** [comment]
@SethTisue here we go
